import { InvalidArgumentError } from '../error';
export { InvalidArgumentError };
export declare function takeAsync<T>(iterable: AsyncIterable<T>, count: number): AsyncIterable<T>;
