import { InvalidArgumentError } from '../error';
export { InvalidArgumentError };
export declare function repeatAsync<T>(iterable: AsyncIterable<T>, times: number): AsyncIterable<T>;
